[package]
name = "benford"
version = "0.1.0"
authors = ["AnikinNikita <nikita.anikin@neuro-city.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
